<%@ Page Title="" Language="C#" MasterPageFile="~/Help/Help.master" AutoEventWireup="true"
    CodeFile="understanding-complexes.aspx.cs" Inherits="Help_UnderstandingData_understanding_complexes" %>

<asp:Content ID="Content1" ContentPlaceHolderID="ContentPlaceHolder1" runat="Server">
    <h3 id="top">
        Understanding Data About Complexes</h3>
    <blockquote>
        Complex ID | Complex Name | Complex Address | Contact Person | Contact Number |
        Policy Number</blockquote>
    <table class="helpTable">
        <tr>
            <td width="20%">
                Column Name
            </td>
            <td width="20%">
                Data Type(length)
            </td>
            <td width="60%">
                Description
            </td>
        </tr>
        <tr>
            <td>
                Complex ID
            </td>
            <td>
                integer
            </td>
            <td>
                <p>
                    The Complex ID column provides a value that is used to identify the record to the
                    rest of the database.<br />
                    The value for this column is automatically generated by the database for each new
                    complex that gets saved.</p>
                <p>
                    This value is only needed by the user when bulk uploading Units (see
                    <asp:HyperLink runat="server" ID="lnkBulkUpload" NavigateUrl="~/Help/DataManagement/bulk-upload.aspx#add-unit"
                        Text="Bulk Upload"></asp:HyperLink>).</p>
            </td>
        </tr>
        <tr>
            <td>
                Complex Name
            </td>
            <td>
                text(100)
            </td>
            <td>
                <p>
                    The name of the complex.<br />
                    This required field is used to filter a selection of units. There is no limitation
                    on what you can use as a complex name as long as it's 100 characters long or less</p>
            </td>
        </tr>
        <tr>
            <td>
                Complex Address
            </td>
            <td>
                text(300)
            </td>
            <td>
                <p>
                    The street address for the complex.<br />
                    Typically a complex address is captured as &lt;Street Address&gt;;&lt;Suburb&gt;</p>
                <p>
                    NOTE: Do not use a comma (,) to separate the street address and suburb as this can
                    lead to data corruption in the system.</p>
            </td>
        </tr>
        <tr>
            <td>
                Contact Person
            </td>
            <td>
                text(100)
            </td>
            <td>
                <p>
                    Your liason in the complex.<br />
                    This could be the owner of the complex, a representative of the board of trustees
                    or the caretaker at the complex.</p>
            </td>
        </tr>
        <tr>
            <td>
                Contact Number
            </td>
            <td>
                text(20)
            </td>
            <td>
                <p>
                    The telephone/cellphone number at which you can contact the liason for this complex.</p>
            </td>
        </tr>
        <tr>
            <td>
                Policy Number
            </td>
            <td>
                integer
            </td>
            <td>
                <p>
                    The unique policy number for the complex.</p>
                <p>
                    This value is input via selection of insurance company and policies that belong
                    to it.</p>
            </td>
        </tr>
    </table>

    <div style="text-align: right;">
        <a href="#top">Back To Top</a>
    </div>
</asp:Content>
